from __future__ import annotations

import hashlib
import html
import re
from pathlib import Path
from typing import Any, Iterator

from docx import Document as load_docx_document
from docx.document import Document as DocxDocumentObject
from docx.oxml.ns import qn
from docx.oxml.table import CT_Tbl
from docx.oxml.text.paragraph import CT_P
from docx.table import Table as DocxTable, _Cell
from docx.text.paragraph import Paragraph as DocxParagraph

from premium_tools import detect_toolchain
from publication_model import PublicationAnalysis, PublicationBlock, PublicationDocument, PublicationSection

TECHNICAL_TITLE_MARKERS = (
    "python-docx",
    "ebooklib",
    "kindlemaster",
    "technical converter",
    "generated by",
    "converted by",
)
TECHNICAL_AUTHOR_MARKERS = (
    "python-docx",
    "ebooklib",
    "kindlemaster",
    "technical converter",
    "generated",
    "converter",
    "creator",
    "producer",
    "unknown",
)
HEADING_STYLE_RE = re.compile(r"heading\s*(?P<level>[1-6])", re.IGNORECASE)


def analyze_docx(docx_path: str | Path) -> dict[str, Any]:
    resolved_path = Path(docx_path).resolve()
    document = load_docx_document(str(resolved_path))
    counts = _count_docx_features(document)
    properties = document.core_properties
    title = _sanitize_docx_title(properties.title or resolved_path.stem, file_stem=resolved_path.stem)
    author = _sanitize_docx_author(properties.author)
    estimated_sections = max(counts["heading1_count"], 1)
    confidence = 0.98 if counts["heading1_count"] else 0.9
    has_toc = counts["heading1_count"] > 1 or counts["heading2_count"] > 0
    analysis = {
        "source_type": "docx",
        "profile": "docx_reflow",
        "recommended_strategy": "docx_reflow",
        "title": title or resolved_path.stem,
        "author": author,
        "paragraph_count": counts["paragraph_count"],
        "heading1_count": counts["heading1_count"],
        "heading2_count": counts["heading2_count"],
        "heading3_count": counts["heading3_count"],
        "list_count": counts["list_count"],
        "table_count": counts["table_count"],
        "image_count": counts["image_count"],
        "hyperlink_count": counts["hyperlink_count"],
        "estimated_sections": estimated_sections,
        "has_title_metadata": bool(_normalize_space(properties.title or "")),
        "has_author_metadata": bool(_normalize_space(properties.author or "")) and author != "Unknown",
        "page_count": 0,
        "text_pages": 0,
        "image_pages": 0,
        "scanned_pages": 0,
        "has_text_layer": True,
        "has_images": counts["image_count"] > 0,
        "is_scanned": False,
        "layout_heavy": False,
        "text_heavy": True,
        "profile_reason": "DOCX structural analysis based on headings, lists, tables, images, and hyperlinks.",
        "publication_analysis": {
            "profile": "docx_reflow",
            "confidence": confidence,
            "has_toc": has_toc,
            "has_tables": counts["table_count"] > 0,
            "has_diagrams": False,
            "has_meaningful_images": counts["image_count"] > 0,
            "estimated_sections": estimated_sections,
            "fallback_recommendation": "",
            "ui_profile": "book",
            "legacy_strategy": "docx_reflow",
            "has_text_layer": True,
            "is_scanned": False,
            "layout_heavy": False,
            "text_heavy": True,
            "scanned_pages": 0,
            "text_pages": 0,
            "image_pages": 0,
            "estimated_columns": 1,
            "heading_density": 1.0 if counts["heading1_count"] else 0.6,
            "font_consistency": 1.0,
            "detected_features": _detected_docx_features(counts, has_toc=has_toc),
            "external_tools": detect_toolchain(),
            "profile_reason": "DOCX reflow profile selected from document structure rather than page geometry.",
        },
    }
    return analysis


def build_docx_publication_document(
    docx_path: str | Path,
    *,
    language: str,
) -> PublicationDocument:
    resolved_path = Path(docx_path).resolve()
    document = load_docx_document(str(resolved_path))
    analysis_payload = analyze_docx(resolved_path)
    publication_payload = analysis_payload["publication_analysis"]
    properties = document.core_properties
    title = _sanitize_docx_title(properties.title or resolved_path.stem, file_stem=resolved_path.stem) or resolved_path.stem
    author = _sanitize_docx_author(properties.author)

    has_heading1 = analysis_payload["heading1_count"] > 0
    fallback_section_title = _pick_fallback_section_title(document, fallback=title or resolved_path.stem)
    sections: list[PublicationSection] = []
    current_section: PublicationSection | None = None
    pending_list: dict[str, Any] | None = None
    asset_registry: dict[str, dict[str, Any]] = {}

    def flush_list() -> None:
        nonlocal pending_list
        if pending_list and current_section is not None and pending_list.get("items"):
            current_section.blocks.append(
                PublicationBlock(
                    block_type="raw_html",
                    raw_html=_build_list_html(pending_list["kind"], pending_list["items"]),
                    text=" ".join(_strip_html(item) for item in pending_list["items"]),
                    source_type="mixed",
                    confidence=0.94,
                )
            )
        pending_list = None

    def ensure_section(section_title: str | None = None) -> PublicationSection:
        nonlocal current_section
        if current_section is None:
            current_section = PublicationSection(
                section_id=f"section-{len(sections) + 1:03d}",
                title=section_title or fallback_section_title,
                level=1,
                kind="section",
                confidence=publication_payload["confidence"],
                page_start=max(len(sections), 0),
                page_end=max(len(sections), 0),
                assets=[],
                metadata={"source_type": "docx"},
            )
            sections.append(current_section)
        return current_section

    for kind, block in _iter_block_items(document):
        if kind == "table":
            section = ensure_section()
            flush_list()
            table_html, table_assets = _table_to_html(block, asset_registry=asset_registry)
            for asset in table_assets:
                if not any(existing.get("filename") == asset["filename"] for existing in section.assets):
                    section.assets.append(asset)
            if table_html:
                section.blocks.append(
                    PublicationBlock(
                        block_type="table",
                        raw_html=table_html,
                        text=_normalize_space(block.cell(0, 0).text if block.rows and block.columns else ""),
                        source_type="mixed",
                        confidence=0.95,
                    )
                )
            continue

        style_name = _paragraph_style_name(block)
        plain_text = _normalize_space(block.text)
        heading_level = _paragraph_heading_level(style_name)

        if heading_level == 1 and plain_text:
            flush_list()
            current_section = PublicationSection(
                section_id=f"section-{len(sections) + 1:03d}",
                title=plain_text,
                level=1,
                kind="section",
                confidence=publication_payload["confidence"],
                page_start=len(sections),
                page_end=len(sections),
                assets=[],
                metadata={"source_type": "docx"},
            )
            sections.append(current_section)
            continue

        section = ensure_section()
        paragraph_html, image_assets, list_kind = _paragraph_to_html(block, asset_registry=asset_registry)

        if image_assets:
            for asset in image_assets:
                if not any(existing.get("filename") == asset["filename"] for existing in section.assets):
                    section.assets.append(asset)

        if list_kind and paragraph_html:
            if pending_list and pending_list.get("kind") == list_kind:
                pending_list["items"].append(paragraph_html)
            else:
                flush_list()
                pending_list = {"kind": list_kind, "items": [paragraph_html]}
            continue

        flush_list()

        if heading_level in {2, 3} and plain_text:
            if not has_heading1 and not section.blocks and plain_text == section.title:
                continue
            section.blocks.append(
                PublicationBlock(
                    block_type="raw_html",
                    raw_html=f"<h{heading_level}>{html.escape(plain_text)}</h{heading_level}>",
                    text=plain_text,
                    source_type="text",
                    confidence=0.95,
                )
            )
            continue

        if paragraph_html:
            tag_name = "blockquote" if "quote" in style_name.lower() else "p"
            raw_html = paragraph_html if tag_name != "p" else f"<p>{paragraph_html}</p>"
            if tag_name == "blockquote":
                raw_html = f"<blockquote><p>{paragraph_html}</p></blockquote>"
            section.blocks.append(
                PublicationBlock(
                    block_type="paragraph",
                    raw_html=raw_html,
                    text=plain_text,
                    source_type="mixed",
                    confidence=0.92,
                )
            )

        for asset in image_assets:
            section.blocks.append(
                PublicationBlock(
                    block_type="figure",
                    raw_html=(
                        f'<figure class="figure illustration"><img src="images/{html.escape(asset["filename"])}" '
                        f'alt="{html.escape(asset.get("alt", ""))}"/></figure>'
                    ),
                    text=asset.get("alt", ""),
                    source_type="image",
                    confidence=0.95,
                    asset_name=asset["filename"],
                    alt_text=asset.get("alt", ""),
                )
            )

    flush_list()

    if not sections:
        sections.append(
            PublicationSection(
                section_id="section-001",
                title=fallback_section_title,
                level=1,
                kind="section",
                confidence=publication_payload["confidence"],
                assets=[],
                metadata={"source_type": "docx"},
            )
        )

    all_assets = _merge_assets([asset for section in sections for asset in section.assets])
    analysis = PublicationAnalysis(
        profile="docx_reflow",
        confidence=publication_payload["confidence"],
        page_count=0,
        render_budget_class="fixed_layout_safe",
        has_toc=publication_payload["has_toc"],
        has_tables=publication_payload["has_tables"],
        has_diagrams=False,
        has_meaningful_images=publication_payload["has_meaningful_images"],
        estimated_sections=max(len(sections), 1),
        fallback_recommendation="",
        ui_profile="book",
        legacy_strategy="docx_reflow",
        has_text_layer=True,
        is_scanned=False,
        layout_heavy=False,
        text_heavy=True,
        scanned_pages=0,
        text_pages=0,
        image_pages=0,
        estimated_columns=1,
        heading_density=publication_payload["heading_density"],
        font_consistency=publication_payload["font_consistency"],
        detected_features=list(publication_payload["detected_features"]),
        external_tools=publication_payload["external_tools"],
        profile_reason=publication_payload["profile_reason"],
    )
    return PublicationDocument(
        title=title,
        author=author,
        language=language,
        profile="docx_reflow",
        analysis=analysis,
        sections=sections,
        assets=all_assets,
        metadata={
            "layout_mode": "reflowable",
            "source_docx_path": str(resolved_path),
            "estimated_sections": max(len(sections), 1),
        },
    )


def _count_docx_features(document: DocxDocumentObject) -> dict[str, int]:
    counts = {
        "paragraph_count": 0,
        "heading1_count": 0,
        "heading2_count": 0,
        "heading3_count": 0,
        "list_count": 0,
        "table_count": 0,
        "image_count": 0,
        "hyperlink_count": 0,
    }
    for kind, block in _iter_block_items(document):
        if kind == "table":
            counts["table_count"] += 1
            continue
        text = _normalize_space(block.text)
        if text:
            counts["paragraph_count"] += 1
        style_name = _paragraph_style_name(block)
        heading_level = _paragraph_heading_level(style_name)
        if heading_level == 1:
            counts["heading1_count"] += 1
        elif heading_level == 2:
            counts["heading2_count"] += 1
        elif heading_level == 3:
            counts["heading3_count"] += 1
        if _paragraph_list_kind(block):
            counts["list_count"] += 1
        counts["hyperlink_count"] += _paragraph_hyperlink_count(block)
        counts["image_count"] += len(_extract_images_from_xml(block._p, part=block.part, asset_registry={}))
    return counts


def _detected_docx_features(counts: dict[str, int], *, has_toc: bool) -> list[str]:
    features: list[str] = []
    if has_toc:
        features.append("structural-headings")
    if counts["table_count"]:
        features.append("tables")
    if counts["image_count"]:
        features.append("images")
    if counts["hyperlink_count"]:
        features.append("hyperlinks")
    if counts["list_count"]:
        features.append("lists")
    return features


def _iter_block_items(parent: DocxDocumentObject | _Cell) -> Iterator[tuple[str, DocxParagraph | DocxTable]]:
    if isinstance(parent, DocxDocumentObject):
        parent_element = parent.element.body
    else:
        parent_element = parent._tc
    for child in parent_element.iterchildren():
        if isinstance(child, CT_P):
            yield "paragraph", DocxParagraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield "table", DocxTable(child, parent)


def _paragraph_style_name(paragraph: DocxParagraph) -> str:
    try:
        return _normalize_space(paragraph.style.name if paragraph.style is not None else "")
    except Exception:
        return ""


def _paragraph_heading_level(style_name: str) -> int:
    lowered = (style_name or "").strip().lower()
    if lowered == "title":
        return 1
    match = HEADING_STYLE_RE.search(lowered)
    if not match:
        return 0
    return int(match.group("level"))


def _paragraph_list_kind(paragraph: DocxParagraph) -> str | None:
    style_name = _paragraph_style_name(paragraph).lower()
    if paragraph._p.pPr is not None and paragraph._p.pPr.numPr is not None:
        if "number" in style_name or "ordered" in style_name:
            return "ol"
        return "ul"
    if "list bullet" in style_name or style_name.startswith("bullet"):
        return "ul"
    if "list number" in style_name or "number" in style_name:
        return "ol"
    return None


def _paragraph_hyperlink_count(paragraph: DocxParagraph) -> int:
    count = 0
    for child in paragraph._p.iterchildren():
        if child.tag == qn("w:hyperlink"):
            count += 1
    return count


def _paragraph_to_html(
    paragraph: DocxParagraph,
    *,
    asset_registry: dict[str, dict[str, Any]],
) -> tuple[str, list[dict[str, Any]], str | None]:
    parts: list[str] = []
    extracted_assets: list[dict[str, Any]] = []
    for child in paragraph._p.iterchildren():
        if child.tag == qn("w:r"):
            html_part, run_assets = _render_run(child, part=paragraph.part, asset_registry=asset_registry)
            if html_part:
                parts.append(html_part)
            extracted_assets.extend(run_assets)
        elif child.tag == qn("w:hyperlink"):
            rel_id = child.get(qn("r:id"))
            href = ""
            if rel_id and rel_id in paragraph.part.rels:
                href = _normalize_space(paragraph.part.rels[rel_id].target_ref)
            hyperlink_parts: list[str] = []
            for run_node in child.iterchildren():
                if run_node.tag != qn("w:r"):
                    continue
                html_part, run_assets = _render_run(run_node, part=paragraph.part, asset_registry=asset_registry)
                if html_part:
                    hyperlink_parts.append(html_part)
                extracted_assets.extend(run_assets)
            link_html = "".join(hyperlink_parts).strip()
            if link_html and href:
                parts.append(f'<a href="{html.escape(href)}">{link_html}</a>')
            elif link_html:
                parts.append(link_html)
    inner_html = "".join(parts).strip()
    return inner_html, _merge_assets(extracted_assets), _paragraph_list_kind(paragraph)


def _render_run(run_node: Any, *, part: Any, asset_registry: dict[str, dict[str, Any]]) -> tuple[str, list[dict[str, Any]]]:
    html_parts: list[str] = []
    assets = _extract_images_from_xml(run_node, part=part, asset_registry=asset_registry)
    rpr = run_node.find(qn("w:rPr"))
    is_bold = rpr is not None and rpr.find(qn("w:b")) is not None
    is_italic = rpr is not None and rpr.find(qn("w:i")) is not None

    for child in run_node.iterchildren():
        if child.tag == qn("w:t"):
            html_parts.append(html.escape(child.text or ""))
        elif child.tag in {qn("w:tab"), qn("w:noBreakHyphen")}:
            html_parts.append(" ")
        elif child.tag in {qn("w:br"), qn("w:cr")}:
            html_parts.append("<br/>")

    text_html = "".join(html_parts)
    if text_html:
        if is_bold:
            text_html = f"<strong>{text_html}</strong>"
        if is_italic:
            text_html = f"<em>{text_html}</em>"
    return text_html, assets


def _extract_images_from_xml(element: Any, *, part: Any, asset_registry: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    assets: list[dict[str, Any]] = []
    for blip in element.xpath('.//*[local-name()="blip"]'):
        rel_id = blip.get(qn("r:embed"))
        if not rel_id:
            continue
        related_part = part.related_parts.get(rel_id)
        if related_part is None:
            continue
        blob = getattr(related_part, "blob", b"")
        if not blob:
            continue
        digest = hashlib.sha1(blob).hexdigest()[:16]
        if digest in asset_registry:
            assets.append(asset_registry[digest])
            continue
        extension = Path(str(getattr(related_part, "partname", "image.png"))).suffix.lstrip(".").lower() or "png"
        if extension == "jpg":
            extension = "jpeg"
        asset = {
            "filename": f"docx_{digest}.{extension}",
            "data": blob,
            "extension": extension,
            "inline": True,
            "alt": "",
        }
        asset_registry[digest] = asset
        assets.append(asset)
    return assets


def _table_to_html(
    table: DocxTable,
    *,
    asset_registry: dict[str, dict[str, Any]],
) -> tuple[str, list[dict[str, Any]]]:
    rows_html: list[str] = []
    extracted_assets: list[dict[str, Any]] = []
    for row in table.rows:
        cells_html: list[str] = []
        for cell in row.cells:
            cell_html, cell_assets = _cell_to_html(cell, asset_registry=asset_registry)
            extracted_assets.extend(cell_assets)
            tag_name = "th" if not rows_html else "td"
            cells_html.append(f"<{tag_name}>{cell_html}</{tag_name}>")
        rows_html.append(f"<tr>{''.join(cells_html)}</tr>")
    if not rows_html:
        return "", []
    return f"<table>{''.join(rows_html)}</table>", _merge_assets(extracted_assets)


def _cell_to_html(
    cell: _Cell,
    *,
    asset_registry: dict[str, dict[str, Any]],
) -> tuple[str, list[dict[str, Any]]]:
    fragments: list[str] = []
    extracted_assets: list[dict[str, Any]] = []
    for kind, block in _iter_block_items(cell):
        if kind == "table":
            nested, nested_assets = _table_to_html(block, asset_registry=asset_registry)
            if nested:
                fragments.append(nested)
            extracted_assets.extend(nested_assets)
            continue
        inner_html, paragraph_assets, list_kind = _paragraph_to_html(block, asset_registry=asset_registry)
        extracted_assets.extend(paragraph_assets)
        inline_asset_html = "".join(
            (
                f'<img src="images/{html.escape(asset["filename"])}" '
                f'alt="{html.escape(asset.get("alt", ""))}"/>'
            )
            for asset in paragraph_assets
        )
        combined_html = f"{inner_html}{inline_asset_html}".strip()
        if not combined_html:
            combined_html = html.escape(_normalize_space(block.text))
        if not combined_html:
            continue
        if list_kind:
            fragments.append(f"<{list_kind}><li>{combined_html}</li></{list_kind}>")
        else:
            fragments.append(f"<p>{combined_html}</p>")
    return "".join(fragments) or "&nbsp;", _merge_assets(extracted_assets)


def _build_list_html(kind: str, items: list[str]) -> str:
    safe_kind = "ol" if kind == "ol" else "ul"
    return f"<{safe_kind}>{''.join(f'<li>{item}</li>' for item in items)}</{safe_kind}>"


def _pick_fallback_section_title(document: DocxDocumentObject, *, fallback: str) -> str:
    for kind, block in _iter_block_items(document):
        if kind != "paragraph":
            continue
        text = _normalize_space(block.text)
        if not text:
            continue
        style_name = _paragraph_style_name(block)
        if _paragraph_heading_level(style_name) in {1, 2, 3} or style_name.lower() == "title":
            return text
    return fallback


def _sanitize_docx_title(value: str | None, *, file_stem: str = "") -> str:
    text = _normalize_space(value or "")
    if not text:
        return ""
    lowered = text.lower()
    if any(marker in lowered for marker in TECHNICAL_TITLE_MARKERS):
        return ""
    if file_stem and lowered == _normalize_space(file_stem).lower():
        return ""
    if re.fullmatch(r"[0-9A-Fa-f]{12,}", text):
        return ""
    return text


def _sanitize_docx_author(value: str | None) -> str:
    text = _normalize_space(value or "")
    if not text:
        return "Unknown"
    lowered = text.lower()
    if any(marker in lowered for marker in TECHNICAL_AUTHOR_MARKERS):
        return "Unknown"
    return text or "Unknown"


def _normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def _strip_html(value: str) -> str:
    return _normalize_space(re.sub(r"<[^>]+>", " ", value or ""))


def _merge_assets(assets: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged: list[dict[str, Any]] = []
    seen: set[str] = set()
    for asset in assets:
        filename = asset.get("filename")
        if not filename or filename in seen:
            continue
        seen.add(filename)
        merged.append(asset)
    return merged
