from __future__ import annotations

import html as html_module
from pathlib import Path
import re

from bs4 import BeautifulSoup
import fitz

from premium_tools import detect_toolchain, run_epubcheck
from publication_model import (
    PublicationAnalysis,
    PublicationBlock,
    PublicationDocument,
    PublicationQualityReport,
    PublicationSection,
)
from text_normalization import ocr_text_to_html_parts as build_normalized_ocr_html_parts
from toc_segmentation import normalize_toc_entries, select_section_outline_entries

TECHNICAL_TITLE_MARKERS = (
    "emvc",
    "pdfdrive",
    "python-docx",
    "kindlemaster",
    "ebooklib",
    "technical converter",
    "generated by",
    "converted by",
)
TECHNICAL_AUTHOR_MARKERS = (
    "dvips",
    "radical eye software",
    "ghostscript",
    "adobe",
    "acrobat",
    "pdf",
    "creator",
    "producer",
    "copyright",
    "python-docx",
    "ebooklib",
    "kindlemaster",
    "technical converter",
    "generated",
    "converter",
    "openai",
    "chatgpt",
    "codex",
)
OCR_HEADING_REJECT_RE = re.compile(
    r"(?i)\b(?:material sponsorowany|materiaĹ‚ sponsorowany|advertorial|reklama|www\.|https?://|doi:)\b"
)
OCR_VALUE_LINE_RE = re.compile(
    r"(?i)(?:\b\d+[.,]\s+\d+%|\b\d+[.,]?\d*\s*(?:%|PLN|USD|EUR|GBP|zł|kg|g|mg|km|m|cm|mm|MB|GB|TB|ms|s|h|pkt)\b)"
)


def build_publication_document(pdf_path: str, config, analysis: PublicationAnalysis) -> PublicationDocument:
    from converter import _extract_pdf_metadata, extract_pdf_with_pymupdf

    pdf_metadata = _extract_pdf_metadata(pdf_path)
    file_stem = Path(pdf_path).stem
    title = _sanitize_publication_title(pdf_metadata.get("title") or file_stem, file_stem=file_stem) or file_stem
    author = _sanitize_publication_author(pdf_metadata.get("author") or "Unknown")

    if analysis.profile == "magazine_reflow":
        from magazine_kindle_reflow import convert_magazine_to_kindle_reflow

        content = convert_magazine_to_kindle_reflow(pdf_path, config=config)
    elif analysis.profile == "diagram_book_reflow":
        from pymupdf_chess_extractor import extract_pdf_with_chess_support

        content = extract_pdf_with_chess_support(pdf_path, config, pdf_metadata)
        content = _coalesce_page_chapters(content, pdf_path, profile=analysis.profile)
    elif analysis.profile == "scanned_reflow":
        content = _build_scanned_content(pdf_path, config, pdf_metadata)
    elif analysis.profile == "book_reflow":
        from premium_reflow import extract_book_premium

        content = extract_book_premium(pdf_path, config=config, pdf_metadata=pdf_metadata)
    else:
        content = extract_pdf_with_pymupdf(pdf_path, config, pdf_metadata)

    content_metadata = content.get("metadata") or {}
    inferred_title = content_metadata.get("inferred_publication_title") or content_metadata.get("title")
    inferred_title = _sanitize_publication_title(inferred_title, file_stem=file_stem)
    if inferred_title and _is_weak_publication_title(title, file_stem=file_stem):
        title = inferred_title
    inferred_author = content_metadata.get("author")
    inferred_author = _sanitize_publication_author(inferred_author)
    if inferred_author and _is_weak_publication_author(author):
        author = inferred_author

    document = publication_from_content(content, analysis, title=title, author=author, language=config.language)
    document.metadata["source_content_method"] = content.get("method", "unknown")
    document.metadata["source_pdf_path"] = pdf_path
    document.metadata["detected_toc_entries"] = len(content.get("toc", []))
    if content.get("metadata"):
        document.metadata["source_metadata"] = content.get("metadata")
    if content.get("audit"):
        document.metadata["audit"] = content.get("audit")
    return document


def _sanitize_publication_title(value: str | None, *, file_stem: str = "") -> str:
    text = (value or "").strip()
    if not text:
        return ""
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\(\s*PDFDrive\s*\)", "", text, flags=re.IGNORECASE).strip(" -_")
    if re.fullmatch(r"[0-9A-Fa-f]{12,}", text):
        return ""
    if _looks_technical_publication_title(text, file_stem=file_stem):
        return ""
    return text


def _sanitize_publication_author(value: str | None) -> str:
    text = (value or "").strip()
    if not text:
        return "Unknown"
    if _looks_technical_publication_author(text):
        return "Unknown"
    text = re.sub(r"\s+", " ", text).strip()
    return text or "Unknown"


def _looks_technical_publication_title(value: str, *, file_stem: str = "") -> bool:
    normalized = re.sub(r"\s+", " ", (value or "").strip())
    if not normalized:
        return True
    lowered = normalized.lower()
    if any(marker in lowered for marker in TECHNICAL_TITLE_MARKERS):
        return True
    if file_stem and lowered == re.sub(r"\s+", " ", file_stem.strip()).lower():
        return True
    return False


def _looks_technical_publication_author(value: str) -> bool:
    normalized = re.sub(r"\s+", " ", (value or "").strip())
    if not normalized:
        return True
    lowered = normalized.lower()
    if lowered in {"unknown", "author", "creator"}:
        return True
    if any(marker in lowered for marker in TECHNICAL_AUTHOR_MARKERS):
        return True
    return False


def _is_weak_publication_title(value: str | None, *, file_stem: str = "") -> bool:
    normalized = re.sub(r"\s+", " ", (value or "").strip())
    return not normalized or re.fullmatch(r"[0-9A-Fa-f]{12,}", normalized or "") is not None or _looks_technical_publication_title(normalized, file_stem=file_stem)


def _is_weak_publication_author(value: str | None) -> bool:
    normalized = re.sub(r"\s+", " ", (value or "").strip())
    return not normalized or normalized == "Unknown" or _looks_technical_publication_author(normalized)


def publication_from_content(
    content: dict,
    analysis: PublicationAnalysis,
    *,
    title: str,
    author: str,
    language: str,
) -> PublicationDocument:
    global_assets = list(content.get("images", []))
    sections: list[PublicationSection] = []
    fallback_pages: list[int] = []
    fallback_regions: list[dict] = []

    for index, chapter in enumerate(content.get("chapters", []), start=1):
        section_title = chapter.get("title") or f"Sekcja {index}"
        page_start = int(chapter.get("_page_start", chapter.get("page_num", index - 1)))
        page_end = int(chapter.get("_page_end", page_start))
        section = PublicationSection(
            section_id=f"section-{index:03d}",
            title=section_title,
            level=1,
            kind=chapter.get("_kind") or _infer_section_kind(section_title, index=index),
            confidence=analysis.confidence,
            page_start=page_start,
            page_end=page_end,
            assets=list(chapter.get("images", [])),
            metadata={
                "source_page_label": chapter.get("_source_page_label"),
                "page_count": (page_end - page_start + 1),
                "fallback_mode": chapter.get("_fallback_mode", ""),
                "audit": chapter.get("_audit", {}),
            },
        )

        for fragment in chapter.get("html_parts", []):
            section.blocks.extend(_fragment_to_blocks(fragment, page_index=page_start))

        if not section.blocks:
            fallback_pages.append(index)
            fallback_regions.append(
                {
                    "section_id": section.section_id,
                    "section_title": section.title,
                    "page_start": page_start + 1,
                    "page_end": page_end + 1,
                    "reason": "empty-section-after-extraction",
                }
            )
        elif chapter.get("_fallback_mode"):
            fallback_regions.append(
                {
                    "section_id": section.section_id,
                    "section_title": section.title,
                    "page_start": page_start + 1,
                    "page_end": page_end + 1,
                    "reason": chapter.get("_fallback_mode"),
                }
            )

        sections.append(section)

    section_assets: list[dict] = []
    for section in sections:
        section_assets.extend(section.assets)
    all_assets = _merge_assets(global_assets + section_assets)

    figure_count = sum(1 for section in sections for block in section.blocks if block.block_type == "figure")
    diagram_count = sum(1 for section in sections for block in section.blocks if block.block_type == "diagram")
    table_count = sum(1 for section in sections for block in section.blocks if block.block_type == "table")
    page_marker_count = sum(1 for section in sections for block in section.blocks if block.block_type == "page_marker")
    asset_figure_count = sum(1 for asset in all_assets if not asset.get("is_chess"))
    asset_diagram_count = sum(1 for asset in all_assets if asset.get("is_chess"))
    report = PublicationQualityReport(
        section_count=len(sections),
        figure_count=max(figure_count, asset_figure_count),
        diagram_count=max(diagram_count, asset_diagram_count),
        table_count=table_count,
        page_marker_count=page_marker_count,
        detected_figures=max(figure_count, asset_figure_count),
        detected_diagrams=max(diagram_count, asset_diagram_count, int(analysis.has_diagrams)),
        detected_tables=table_count,
        fallback_pages=fallback_pages,
        fallback_sections=[sections[idx - 1].title for idx in fallback_pages if 0 < idx <= len(sections)],
        fallback_regions=fallback_regions,
        high_risk_sections=_build_high_risk_sections(sections, content),
        high_risk_pages=((content.get("audit") or {}).get("high_risk_pages") or []),
        warnings=_build_document_warnings(
            analysis=analysis,
            sections=sections,
            content=content,
            fallback_pages=fallback_pages,
        ),
        external_tools_used=analysis.external_tools,
    )

    return PublicationDocument(
        title=title,
        author=author,
        language=language,
        profile=analysis.profile,
        analysis=analysis,
        sections=sections,
        assets=all_assets,
        metadata={
            "layout_mode": content.get("layout_mode", "reflowable"),
            "estimated_sections": analysis.estimated_sections,
        },
        quality_report=report,
    )


def publication_to_content(document: PublicationDocument) -> dict:
    chapters = []
    for section in document.sections:
        html_parts = []
        for block in section.blocks:
            fragment = _block_to_fragment(block)
            if fragment:
                html_parts.append(fragment)
        chapter = {
            "title": section.title,
            "html_parts": html_parts,
            "images": list(section.assets),
        }
        if section.metadata.get("source_page_label"):
            chapter["_source_page_label"] = section.metadata["source_page_label"]
        chapter["_page_start"] = section.page_start
        chapter["_page_end"] = section.page_end
        chapters.append(chapter)

    return {
        "success": True,
        "method": "publication-model",
        "text_content": True,
        "layout_mode": document.metadata.get("layout_mode", "reflowable"),
        "images": document.assets,
        "chapters": chapters,
    }


def finalize_publication_epub(document: PublicationDocument, epub_bytes: bytes) -> PublicationQualityReport:
    validation = run_epubcheck(epub_bytes)
    document.quality_report.validation_status = validation["status"]
    document.quality_report.validation_messages = validation["messages"]
    document.quality_report.validation_tool = validation["tool"]
    if validation["status"] != "passed":
        if validation["status"] == "unavailable":
            document.quality_report.warnings.append("Formalna walidacja EPUBCheck nie mogla zostac wykonana.")
        else:
            document.quality_report.warnings.append("EPUBCheck zglosil problemy wymagajace poprawy przed release.")
    if not document.quality_report.external_tools_used:
        document.quality_report.external_tools_used = detect_toolchain()
    return document.quality_report


def _build_scanned_content(pdf_path: str, config, pdf_metadata: dict) -> dict:
    from converter import OCR_AVAILABLE, _build_content_from_ocr, extract_pdf_with_pymupdf

    if OCR_AVAILABLE and config.enable_external_ocr:
        try:
            from ocr_module import check_ocrmypdf_ready, get_best_available_engine, run_ocr_on_page, run_ocr_on_pdf

            full_ocr_result = None
            if check_ocrmypdf_ready():
                full_ocr_result = run_ocr_on_pdf(pdf_path, language=config.ocr_language, dpi=300)
                if full_ocr_result.engine_used == "ocrmypdf" and full_ocr_result.success_rate >= 0.5:
                    return _build_content_from_ocr(full_ocr_result, config, pdf_metadata)

            baseline_content = extract_pdf_with_pymupdf(pdf_path, config, pdf_metadata)
            chapters = list(baseline_content.get("chapters", []))
            if not chapters:
                if full_ocr_result is None:
                    full_ocr_result = run_ocr_on_pdf(pdf_path, language=config.ocr_language, dpi=300)
                return _build_content_from_ocr(full_ocr_result, config, pdf_metadata)

            doc = fitz.open(pdf_path)
            try:
                selected_engine = get_best_available_engine()
                ocr_pages = 0
                hybrid_images = list(baseline_content.get("images", []))

                for chapter in chapters:
                    page_num = int(chapter.get("page_num", -1))
                    if page_num < 0 or page_num >= len(doc):
                        continue

                    plain_text = _chapter_plain_text(chapter)
                    is_low_text_page = len(plain_text) < 180 or len(chapter.get("html_parts", [])) <= 1
                    if not is_low_text_page:
                        continue

                    ocr_page = run_ocr_on_page(
                        doc[page_num],
                        page_num=page_num,
                        language=config.ocr_language,
                        dpi=300,
                        engine=selected_engine,
                    )
                    if len((ocr_page.text or "").strip()) < 80:
                        continue

                    ocr_confidence = ocr_page.confidence
                    chapter["html_parts"] = _ocr_text_to_html_parts(ocr_page.text)
                    chapter["_fallback_mode"] = "ocr-page"
                    chapter["ocr_confidence"] = ocr_confidence
                    ocr_pages += 1

                    if ocr_confidence < 0.62:
                        img_filename = f"ocr_page_{page_num}.jpeg"
                        image_asset = {
                            "filename": img_filename,
                            "data": ocr_page.image_data,
                            "extension": "jpeg",
                            "page": page_num,
                            "ocr_text": ocr_page.text,
                            "confidence": ocr_confidence,
                        }
                        hybrid_images.append(image_asset)
                        chapter.setdefault("images", []).append(image_asset)
                        chapter["html_parts"].append(
                            f'<figure class="figure illustration"><img src="images/{img_filename}" alt="Strona referencyjna po OCR"/></figure>'
                        )

                baseline_content["images"] = _merge_content_assets(hybrid_images)
                if ocr_pages:
                    baseline_content["method"] = f"{baseline_content.get('method', 'pymupdf')}-hybrid-ocr"
                return baseline_content
            finally:
                doc.close()
        except Exception:
            pass
    return extract_pdf_with_pymupdf(pdf_path, config, pdf_metadata)


def _chapter_plain_text(chapter: dict) -> str:
    html_parts = chapter.get("html_parts", [])
    if not html_parts:
        return ""
    soup = BeautifulSoup("".join(html_parts), "xml")
    return soup.get_text(" ", strip=True)


def _legacy_ocr_text_to_html_parts(text: str) -> list[str]:

    normalized = re.sub(r"\r\n?", "\n", text or "")
    blocks = [block.strip() for block in re.split(r"\n\s*\n+", normalized) if block.strip()]
    html_parts: list[str] = []

    for index, block in enumerate(blocks):
        lines = [re.sub(r"\s+", " ", line).strip() for line in block.split("\n") if line.strip()]
        if not lines:
            continue
        heading_line = None
        if len(lines) > 1:
            tail = lines[-1]
            if _looks_like_ocr_heading_line(tail):
                heading_line = tail
                lines = lines[:-1]
            elif _looks_like_ocr_heading_line(lines[0]) and len(lines[0].split()) <= 8:
                heading_line = lines[0]
                lines = lines[1:]

        merged = " ".join(lines)
        merged = re.sub(r"(?<=\w)- (?=\w)", "", merged)
        merged = re.sub(r"\s+", " ", merged).strip()
        if index == 0 and merged and len(merged.split()) <= 10 and merged[:1].isupper():
            html_parts.append(f"<h1>{html_module.escape(merged)}</h1>")
        elif merged:
            html_parts.append(f"<p>{html_module.escape(merged)}</p>")
        if heading_line:
            tag = "h2" if re.match(r"(?i)^(chapter|rozdział|appendix|dodatek)\b", heading_line) else "h3"
            html_parts.append(f"<{tag}>{html_module.escape(heading_line)}</{tag}>")

    return html_parts


def _ocr_text_to_html_parts(text: str) -> list[str]:
    return build_normalized_ocr_html_parts(text)


def _looks_like_ocr_heading_line(line: str) -> bool:
    candidate = re.sub(r"\s+", " ", (line or "").strip())
    if not candidate or len(candidate) > 120:
        return False
    if _looks_like_non_heading_ocr_line(candidate):
        return False
    if re.search(r"[.!?;:]$", candidate):
        return False
    if re.match(r"(?i)^(chapter|rozdział|appendix|dodatek)\b", candidate):
        return True
    if re.match(r"^[0-9]+(\.[0-9]+)*\s+[A-Z]", candidate):
        return True
    words = candidate.split()
    if 1 <= len(words) <= 8 and candidate[:1].isupper():
        return sum(word[:1].isupper() for word in words if word[:1].isalpha()) >= max(1, len(words) - 1)
    return False


def _looks_like_non_heading_ocr_line(line: str) -> bool:
    candidate = re.sub(r"\s+", " ", (line or "").strip())
    if not candidate:
        return True
    if candidate.startswith(("-", "*", "•", "")):
        return True
    if OCR_HEADING_REJECT_RE.search(candidate):
        return True
    if OCR_VALUE_LINE_RE.search(candidate):
        return True
    return False


def _merge_content_assets(assets: list[dict]) -> list[dict]:
    merged: list[dict] = []
    seen: set[str] = set()
    for asset in assets:
        filename = asset.get("filename")
        if filename and filename in seen:
            continue
        if filename:
            seen.add(filename)
        merged.append(asset)
    return merged


def _fragment_to_blocks(fragment: str, *, page_index: int) -> list[PublicationBlock]:
    soup = BeautifulSoup(fragment, "xml")
    nodes = [node for node in soup.contents if getattr(node, "name", None)]
    if not nodes and fragment.strip():
        return [PublicationBlock(block_type="raw_html", raw_html=fragment, text=fragment, page_index=page_index, source_type="mixed")]

    blocks: list[PublicationBlock] = []
    for node in nodes:
        blocks.append(_node_to_block(node, page_index))
    return blocks


def _node_to_block(node, page_index: int) -> PublicationBlock:
    text = node.get_text(" ", strip=True)
    name = node.name
    css_class = " ".join(node.get("class", [])) if node.get("class") else None

    if name == "span" and "page-marker" in (css_class or ""):
        return PublicationBlock(
            block_type="page_marker",
            text=node.get("id", ""),
            raw_html=str(node),
            page_index=page_index,
            confidence=1.0,
            source_type="text",
        )
    if name in {"h1", "h2", "h3"}:
        return PublicationBlock(
            block_type="heading" if name == "h1" else "subheading",
            text=text,
            raw_html=str(node),
            page_index=page_index,
            confidence=0.96,
            source_type="text",
            level=int(name[1]),
        )
    if name == "blockquote":
        return PublicationBlock(
            block_type="sidebar",
            text=text,
            raw_html=str(node),
            page_index=page_index,
            confidence=0.82,
            source_type="mixed",
        )
    if name == "figure":
        image = node.find("img")
        return PublicationBlock(
            block_type="figure",
            text=text,
            raw_html=str(node),
            page_index=page_index,
            confidence=0.94,
            source_type="image",
            asset_name=(image.get("src", "").split("/")[-1] if image else None),
            alt_text=image.get("alt") if image else "",
            style_class=css_class,
        )
    if name == "div" and "chess-problem" in (css_class or ""):
        return PublicationBlock(
            block_type="diagram",
            text=text,
            raw_html=str(node),
            page_index=page_index,
            confidence=0.95,
            source_type="mixed",
            style_class=css_class,
        )
    if name == "p":
        block_type = "paragraph"
        if css_class == "toc-entry":
            block_type = "toc_entry"
        elif css_class == "lead":
            block_type = "paragraph"
        elif css_class == "byline":
            block_type = "caption"
        elif css_class == "aside":
            block_type = "sidebar"
        return PublicationBlock(
            block_type=block_type,
            text=text,
            raw_html=str(node),
            page_index=page_index,
            confidence=0.9,
            source_type="text",
            style_class=css_class,
        )
    return PublicationBlock(
        block_type="raw_html",
        text=text,
        raw_html=str(node),
        page_index=page_index,
        confidence=0.6,
        source_type="mixed",
        style_class=css_class,
    )


def _infer_section_kind(section_title: str, *, index: int) -> str:
    normalized = (section_title or "").strip().lower()
    if index == 1 and normalized in {"okładka", "okladka", "cover", "front matter"}:
        return "cover"
    if normalized.startswith("appendix"):
        return "appendix"
    if normalized in {"index", "name index", "opening index"}:
        return "index"
    if normalized in {"glossary", "table of contents", "spis treści", "spis tresci"}:
        return "reference"
    return "section"


def _build_document_warnings(*, analysis: PublicationAnalysis, sections: list[PublicationSection], content: dict, fallback_pages: list[int]) -> list[str]:
    warnings: list[str] = []
    section_count = len(sections)
    if analysis.profile in {"book_reflow", "diagram_book_reflow"} and analysis.has_toc and section_count > max(analysis.estimated_sections * 2, 40):
        warnings.append("Liczba sekcji jest podejrzanie wysoka wzgledem struktury TOC.")
    if analysis.profile == "diagram_book_reflow" and section_count > 80:
        warnings.append("Publikacja z diagramami nadal wyglada na zbyt rozbita na sekcje.")
    if fallback_pages:
        warnings.append(f"Wykryto {len(fallback_pages)} pustych lub fallbackowych sekcji.")
    if not content.get("images") and analysis.has_meaningful_images:
        warnings.append("Analiza wykryla istotne grafiki, ale finalny content ich nie zachowal.")
    audit = content.get("audit") or {}
    high_risk = audit.get("high_risk_chapters") or []
    if high_risk:
        warnings.append(f"Wykryto {len(high_risk)} rozdziałów wysokiego ryzyka wymagających kontroli.")
    high_risk_pages = audit.get("high_risk_pages") or []
    if high_risk_pages:
        warnings.append(f"Wykryto {len(high_risk_pages)} stron wysokiego ryzyka wymagających kontroli.")
    weak_titles = [
        section.title
        for section in sections
        if "weak-chapter-title" in (section.metadata.get("audit", {}) or {}).get("risk_flags", [])
    ]
    if weak_titles:
        warnings.append(f"Wykryto {len(weak_titles)} sekcji ze słabym lub technicznym tytułem.")
    return warnings


def _build_high_risk_sections(sections: list[PublicationSection], content: dict) -> list[dict]:
    audit = content.get("audit") or {}
    chapter_audit_rows = audit.get("chapters") or []
    risk_map = {
        tuple(row.get("page_range", [])): row
        for row in chapter_audit_rows
        if row.get("page_range")
    }
    high_risk_sections: list[dict] = []
    for section in sections:
        row = risk_map.get((section.page_start + 1, section.page_end + 1))
        if not row:
            row = section.metadata.get("audit", {}) or {}
        risk_score = row.get("risk_score", 0)
        if risk_score >= 3:
            high_risk_sections.append(
                {
                    "section_id": section.section_id,
                    "title": section.title,
                    "page_range": [section.page_start + 1, section.page_end + 1],
                    "risk_flags": row.get("risk_flags", []),
                    "risk_score": risk_score,
                }
            )
    return high_risk_sections


def _merge_assets(assets: list[dict]) -> list[dict]:
    merged: list[dict] = []
    seen: set[str] = set()
    for asset in assets:
        filename = asset.get("filename")
        if filename and filename in seen:
            continue
        if filename:
            seen.add(filename)
        merged.append(asset)
    return merged


def _coalesce_page_chapters(content: dict, pdf_path: str, *, profile: str) -> dict:
    chapters = list(content.get("chapters", []))
    if not chapters or "page_num" not in chapters[0]:
        return content

    coalesced = _coalesce_page_chapters_by_toc(content, pdf_path)
    if len(coalesced.get("chapters", [])) != len(chapters):
        return coalesced

    detected = _coalesce_page_chapters_by_detected_titles(content, pdf_path, profile=profile)
    if len(detected.get("chapters", [])) != len(chapters):
        return detected

    return content


def _coalesce_page_chapters_by_toc(content: dict, pdf_path: str) -> dict:
    chapters = list(content.get("chapters", []))
    if not chapters or "page_num" not in chapters[0]:
        return content

    doc = fitz.open(pdf_path)
    toc = doc.get_toc()
    doc.close()
    if not toc:
        return content

    entries = normalize_toc_entries(toc)
    if not entries:
        return content

    outline_entries = select_section_outline_entries(entries)
    if not outline_entries:
        return content

    grouped: list[dict] = []
    for idx, entry in enumerate(outline_entries):
        start = entry["page"]
        end = (outline_entries[idx + 1]["page"] - 1) if idx + 1 < len(outline_entries) else (len(chapters) - 1)
        end = max(start, end)
        page_slice = [chapter for chapter in chapters if start <= int(chapter.get("page_num", -1)) <= end]
        if not page_slice:
            continue

        html_parts: list[str] = []
        images: list[dict] = []
        source_page_label = None
        for chapter in sorted(page_slice, key=lambda item: int(item.get("page_num", 0))):
            if source_page_label is None:
                source_page_label = chapter.get("_source_page_label")
            html_parts.extend(chapter.get("html_parts", []))
            images.extend(chapter.get("images", []))

        grouped.append(
            {
                "title": entry["title"],
                "html_parts": html_parts,
                "images": images,
                "_source_page_label": source_page_label,
                "_page_start": start,
                "_page_end": end,
            }
        )

    if not grouped:
        return content

    return {
        **content,
        "chapters": grouped,
        "method": f"{content.get('method', 'unknown')}-toc-grouped",
        "toc": [(entry["level"], entry["title"], entry["page"] + 1) for entry in outline_entries],
    }


def _coalesce_page_chapters_by_detected_titles(content: dict, pdf_path: str, *, profile: str) -> dict:
    chapters = list(content.get("chapters", []))
    if not chapters or "page_num" not in chapters[0]:
        return content

    entries = _detect_section_entries_from_pages(pdf_path, profile=profile)
    if len(entries) < 2:
        return content

    grouped = _group_page_chapters(chapters, entries)
    if len(grouped) >= len(chapters) or not grouped:
        return content

    toc = [(1, entry["title"], entry["page"] + 1) for entry in entries]
    return {
        **content,
        "chapters": grouped,
        "method": f"{content.get('method', 'unknown')}-title-grouped",
        "toc": toc,
    }


def _detect_section_entries_from_pages(pdf_path: str, *, profile: str) -> list[dict]:
    doc = fitz.open(pdf_path)
    try:
        entries: list[dict] = []
        for page_num in range(len(doc)):
            page = doc[page_num]
            title = _detect_title_page_heading(page)
            if not title:
                title = _detect_running_header_heading(page)
            title = _normalize_section_title_candidate(title)
            if not title:
                continue
            if entries and title == entries[-1]["title"]:
                continue
            if profile == "diagram_book_reflow" and not _looks_like_diagram_section_title(title):
                continue
            entries.append({"page": page_num, "title": title})
        return entries
    finally:
        doc.close()


def _detect_title_page_heading(page: fitz.Page) -> str:
    blocks = page.get_text("dict", sort=True).get("blocks", [])
    candidates: list[tuple[float, float, str]] = []
    body_sizes: list[float] = []

    for block in blocks:
        if block.get("type") != 0:
            continue
        bbox = block.get("bbox", (0, 0, 0, 0))
        text_parts: list[str] = []
        sizes: list[float] = []
        font_tokens: list[str] = []
        for line in block.get("lines", []):
            for span in line.get("spans", []):
                text = (span.get("text") or "").strip()
                if not text:
                    continue
                size = float(span.get("size", 0.0))
                sizes.append(size)
                body_sizes.append(size)
                text_parts.append(text)
                font_tokens.append((span.get("font") or "").lower())
        if not text_parts:
            continue
        text = " ".join(text_parts).strip()
        if any(token for token in font_tokens if any(font_name in token for font_name in ("skak", "merida", "chess"))):
            continue
        if _looks_like_noise_title(text):
            continue
        max_size = max(sizes) if sizes else 0.0
        if bbox[1] <= page.rect.height * 0.58 and max_size >= 17.0:
            candidates.append((bbox[1], max_size, text))

    if not candidates:
        return ""

    body_size = sorted(body_sizes)[len(body_sizes) // 2] if body_sizes else 12.0
    strong = [candidate for candidate in candidates if candidate[1] >= max(body_size * 1.45, 17.0)]
    chosen = strong or candidates
    chosen.sort(key=lambda item: (item[0], -item[1]))

    lines: list[str] = []
    for _, _, text in chosen[:4]:
        clean = _normalize_section_title_candidate(text)
        if not clean or clean in lines:
            continue
        lines.append(clean)
        if len(lines) == 3:
            break
    return " - ".join(lines[:2]) if lines else ""


def _detect_running_header_heading(page: fitz.Page) -> str:
    top_lines: list[tuple[float, str]] = []
    for block in page.get_text("dict", sort=True).get("blocks", []):
        if block.get("type") != 0:
            continue
        bbox = block.get("bbox", (0, 0, 0, 0))
        if bbox[1] > min(page.rect.height * 0.16, 110):
            continue
        text_parts: list[str] = []
        fonts: list[str] = []
        for line in block.get("lines", []):
            for span in line.get("spans", []):
                text = (span.get("text") or "").strip()
                if text:
                    text_parts.append(text)
                    fonts.append((span.get("font") or "").lower())
        if not text_parts:
            continue
        if any(any(token in font for token in ("skak", "merida", "chess")) for font in fonts):
            continue
        top_lines.append((bbox[1], " ".join(text_parts)))

    if not top_lines:
        return ""

    top_lines.sort(key=lambda item: item[0])
    header = _normalize_text_title(top_lines[0][1])
    if not header:
        return ""

    match = re.search(r"((?:chapter|part|appendix)\s+\d+[A-Za-z\-]*)", header, re.IGNORECASE)
    if match:
        return match.group(1)

    numbered = re.search(r"(\d+(?:\.\d+)+\s+[A-Za-z][A-Za-z0-9 #&:,\-]+)$", header)
    if numbered:
        return numbered.group(1)

    return ""


def _looks_like_noise_title(text: str) -> bool:
    normalized = _normalize_text_title(text)
    if not normalized:
        return True
    if re.fullmatch(r"[a-h](?:\s+[a-h]){7}(?:\s+\d+)?", normalized, re.IGNORECASE):
        return True
    if re.fullmatch(r"\d+", normalized):
        return True
    return False


def _normalize_text_title(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "").replace("\n", " ")).strip(" -")


def _normalize_section_title_candidate(text: str) -> str:
    normalized = _normalize_text_title(text)
    if not normalized:
        return ""
    normalized = re.sub(r"^5334 Problems, Combinations & Games\s*", "", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"^contents\s*", "", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\b([a-z]{2,})\s*-\s+([a-z]{2,})\b", r"\1\2", normalized)
    normalized = re.sub(r"\s+", " ", normalized).strip(" -")
    if _looks_like_noise_title(normalized):
        return ""
    return normalized


def _looks_like_diagram_section_title(text: str) -> bool:
    lower = text.lower()
    return bool(
        re.search(r"\bchapter\b", lower)
        or re.search(r"\bappendix\b", lower)
        or re.search(r"\bforeword\b|\bintroduction\b|\bcontents\b|\bkey to\b", lower)
        or re.match(r"\d+(?:\.\d+)+\s+\w+", text)
        or len(text.split()) <= 8
    )


def _group_page_chapters(chapters: list[dict], entries: list[dict]) -> list[dict]:
    grouped: list[dict] = []
    for idx, entry in enumerate(entries):
        start = entry["page"]
        end = (entries[idx + 1]["page"] - 1) if idx + 1 < len(entries) else max(int(ch.get("page_num", 0)) for ch in chapters)
        page_slice = [chapter for chapter in chapters if start <= int(chapter.get("page_num", -1)) <= end]
        if not page_slice:
            continue

        html_parts: list[str] = []
        images: list[dict] = []
        source_page_label = None
        for chapter in sorted(page_slice, key=lambda item: int(item.get("page_num", 0))):
            if source_page_label is None:
                source_page_label = chapter.get("_source_page_label")
            html_parts.extend(chapter.get("html_parts", []))
            images.extend(chapter.get("images", []))

        grouped.append(
            {
                "title": entry["title"],
                "html_parts": html_parts,
                "images": images,
                "_source_page_label": source_page_label,
                "_page_start": start,
                "_page_end": end,
            }
        )

    return grouped


def _block_to_fragment(block: PublicationBlock) -> str:
    if block.raw_html:
        raw = block.raw_html.strip()
        if re.fullmatch(r"<ul\s*/>", raw, flags=re.IGNORECASE):
            return "<ul>"
        if re.fullmatch(r"<ol\s*/>", raw, flags=re.IGNORECASE):
            return "<ol>"
        return block.raw_html
    safe_text = html_module.escape(block.text)
    if block.block_type == "heading":
        return f"<h1>{safe_text}</h1>"
    if block.block_type == "subheading":
        return f"<h2>{safe_text}</h2>"
    if block.block_type == "sidebar":
        return f"<blockquote><p>{safe_text}</p></blockquote>"
    if block.block_type == "caption":
        return f'<p class="byline">{safe_text}</p>'
    if block.block_type == "toc_entry":
        return f'<p class="toc-entry">{safe_text}</p>'
    return f"<p>{safe_text}</p>"
