do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'quiz_attempts'
  ) then
    execute 'alter table public.quiz_attempts add column if not exists deck_name text';
    execute 'alter table public.quiz_attempts add column if not exists session_mode text not null default ''mixed''';
    execute 'alter table public.quiz_attempts add column if not exists session_filters jsonb not null default ''{}''::jsonb';
  end if;
end $$;

create table if not exists public.user_deck_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deck text not null,
  exam_name text not null default '',
  exam_description text not null default '',
  target_date date,
  source_notes text not null default '',
  target_score integer not null default 80,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, deck),
  constraint user_deck_goals_target_score_check check (target_score between 50 and 100)
);

create index if not exists user_deck_goals_user_deck_idx
  on public.user_deck_goals (user_id, deck);

alter table public.user_deck_goals enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_deck_goals' and policyname = 'user_deck_goals_select_own'
  ) then
    create policy user_deck_goals_select_own
      on public.user_deck_goals
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_deck_goals' and policyname = 'user_deck_goals_insert_own'
  ) then
    create policy user_deck_goals_insert_own
      on public.user_deck_goals
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_deck_goals' and policyname = 'user_deck_goals_update_own'
  ) then
    create policy user_deck_goals_update_own
      on public.user_deck_goals
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
