alter table public.billing_accounts
  add column if not exists trial_started_at timestamptz,
  add column if not exists trial_ends_at timestamptz;

create table if not exists public.user_usage_monthly (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_key text not null,
  period_start date not null,
  usage_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, usage_key, period_start)
);

create index if not exists user_usage_monthly_user_period_idx
  on public.user_usage_monthly (user_id, period_start desc, usage_key);

alter table public.user_usage_monthly enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_usage_monthly' and policyname = 'user_usage_monthly_select_own'
  ) then
    create policy user_usage_monthly_select_own
      on public.user_usage_monthly
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_usage_monthly' and policyname = 'user_usage_monthly_insert_own'
  ) then
    create policy user_usage_monthly_insert_own
      on public.user_usage_monthly
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_usage_monthly' and policyname = 'user_usage_monthly_update_own'
  ) then
    create policy user_usage_monthly_update_own
      on public.user_usage_monthly
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

create table if not exists public.user_card_states (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  queue text not null default 'new',
  ease_factor numeric(5,2) not null default 2.50,
  interval_days integer not null default 0,
  repetitions integer not null default 0,
  lapses integer not null default 0,
  learning_step integer not null default 0,
  due_at timestamptz not null default timezone('utc', now()),
  last_reviewed_at timestamptz,
  last_result text,
  last_response_ms integer,
  total_reviews integer not null default 0,
  correct_reviews integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, question_id),
  constraint user_card_states_queue_check check (queue in ('new', 'learning', 'review'))
);

create index if not exists user_card_states_user_due_idx
  on public.user_card_states (user_id, due_at asc);

create index if not exists user_card_states_user_queue_idx
  on public.user_card_states (user_id, queue);

alter table public.user_card_states enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_card_states' and policyname = 'user_card_states_select_own'
  ) then
    create policy user_card_states_select_own
      on public.user_card_states
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_card_states' and policyname = 'user_card_states_insert_own'
  ) then
    create policy user_card_states_insert_own
      on public.user_card_states
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_card_states' and policyname = 'user_card_states_update_own'
  ) then
    create policy user_card_states_update_own
      on public.user_card_states
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
