create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_select_own'
  ) then
    create policy profiles_select_own on public.profiles for select using (auth.uid() = id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_insert_own'
  ) then
    create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_update_own'
  ) then
    create policy profiles_update_own on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'quiz_attempts'
  ) then
    execute 'alter table public.quiz_attempts add column if not exists user_id uuid references auth.users(id) on delete cascade';
    execute 'alter table public.quiz_attempts enable row level security';
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'quiz_attempts'
  ) then
    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public' and tablename = 'quiz_attempts' and policyname = 'quiz_attempts_select_own'
    ) then
      create policy quiz_attempts_select_own on public.quiz_attempts for select using (auth.uid() = user_id);
    end if;

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public' and tablename = 'quiz_attempts' and policyname = 'quiz_attempts_insert_own'
    ) then
      create policy quiz_attempts_insert_own on public.quiz_attempts for insert with check (auth.uid() = user_id);
    end if;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'quiz_questions'
  ) then
    execute 'alter table public.quiz_questions add column if not exists tags text[] not null default ''{}''::text[]';
  end if;
end $$;

create table if not exists public.user_question_tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  tags text[] not null default '{}'::text[],
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, question_id)
);

alter table public.user_question_tags enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_question_tags' and policyname = 'user_question_tags_select_own'
  ) then
    create policy user_question_tags_select_own on public.user_question_tags for select using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_question_tags' and policyname = 'user_question_tags_insert_own'
  ) then
    create policy user_question_tags_insert_own on public.user_question_tags for insert with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'user_question_tags' and policyname = 'user_question_tags_update_own'
  ) then
    create policy user_question_tags_update_own on public.user_question_tags for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;
end $$;
